# Generated by Django 3.2.4 on 2021-06-27 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('good_count', models.IntegerField(default=0)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POST_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '投稿データ',
                'verbose_name_plural': '投稿データ',
                'ordering': ('-up_date',),
            },
        ),
    ]
